# Generated by Django 4.2.20 on 2025-04-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_game_is_published_remove_game_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='provider',
            name='email',
            field=models.EmailField(default='no-email@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
